groups:
  default:  # Required by current implementation
    tasks:
      dummy:  # Minimal required task
        help: Default group requirement
        run: echo "Default group exists"

  build:
    env:
      GROUP_ENV: group_value
    tasks:
      clean:
        help: Clean build artifacts
        args:
          cache:
            type: bool
            action: store_true
            help: Remove all cache files
        run: |
          echo "Cleaning build directory..."
          rm -rf build/
      compile:
        help: Compile the project
        hooks:
          pre-run:
            - task: build.clean
        run: |
          echo "Compiling the project..."

scheduler:
  daily-clean:
    task: build.clean
    schedule: "0 0 * * *"